/**
 * dadosConselheiros.js — Descrições biográficas dos conselheiros fundadores
 * Cada constante contém a bio completa de um conselheiro.
 */

export const AlexandreReis = `Administrador de Empresas formado pela GLIESP com mestrado em Gestão pela Universidade Federal Fluminense (UFF) e pós-graduado em Cenários Econômicos pela Universidade Federal do Rio de Janeiro (UFRJ), pós-graduado em Cambio e Comercio Exterior pela FGV, além de especializações no exterior em Governança Corporativa pela University de Cambridge, Planejamento estratégico pela University Wharton e Gestão da Inovação pela University Ensead. Há mais de 35 anos atuando em empresas e instituições, é reconhecido por sua competência no desenvolvimento e desdobramento de estratégias e por sua ampla experiência em liderança e cultura organizacional.`;

export const AmericoOliveira = `Engenheiro civil pela Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio), com pós-graduação em Planejamento Urbano pela Universidade de Dortmund (Alemanha) e cursos de extensão profissional. Conselheiro Certificado pela Fundação Getúlio Vargas (FGV). Possui larga experiência em liderança e implementação de metodologia de governança e estruturação de empresas, tendo exercido posições de diretoria, gerência-geral e presidência em subsidiárias de empresas multinacionais em diferentes países. Suas áreas de interesse incluem a internacionalização, as fusões e aquisições e a diversidade.`;

export const AntonioAlmeidaSJunior = `Engenheiro com MBA em Marketing pela FGV Management (Fundação Getúlio Vargas) e conselheiro certificado pela FGV, com cursos de extensão nas áreas de Inovação pelo Instituto Brasileiro de Governança Corporativa (IBGC), Planejamento Estratégico pelo Institute for Management Development (IMD), na Suíça, e Tecnologia da Informação pela London Business School, em Hong Kong. Possui mais de 47 anos de experiência profissional em empresas nacionais e internacionais, com cargos locais, regionais e internacionais, tendo atuado também como docente e palestrante em cursos de pós-graduação. Suas áreas de concentração incluem o desenvolvimento e desdobramento de estratégias, a digitalização e a cultura organizacional.`;

export const CarlosAlbertoErcolin = `MBA e mestre em Administração pela FEA-USP, possui cursos de pós-graduação no Brasil e no exterior. Conselheiro certificado pelo Instituto Brasileiro de Governança Corporativa (IBGC), onde coordenou o capítulo Paraná. Executivo com mais de 35 anos de experiência em 17 países, atuando em multinacionais de diversos setores. Trabalha também como docente em programas de pós-graduação. Suas áreas de interesse incluem a implantação de conselhos, as fusões e aquisições (M&A) e a sucessão em empresas familiares.`;

export const ClaudiaLeiteFerreira = `Formada em Arquitetura e Urbanismo pela Universidade Federal do Rio de Janeiro (UFRJ), com MBA em Logística Empresarial e mestrado em Gestão de Negócios pela Fundação Getúlio Vargas (FGV), Universidade Católica de Lisboa e Darla Moore Scholl, na Carolina do Sul (EUA). É executiva em Supply Chain, tendo exercido, nos últimos 25 anos, cargos de comando e gestão na área de logística e no agronegócio brasileiro da soja e do milho. Seus temas de interesse incluem a internacionalização, a logística e a diversidade.`;

export const GilbertoAlbueno = `Engenheiro mecânico com especialização em Administração de Empresas pela Fundação Getúlio Vargas (FGV), onde também fez o curso Formação para Conselheiros. Experiência profissional associada à geração de energia e gestão de multinacionais no Brasil, tendo ocupado cargos executivos em diversas empresas multinacionais. Reconhecido por seu compromisso com ética e compliance, crescimento sustentável e valor para a empresa e seus acionistas. Seus interesses estão voltados para a internacionalização, as fusões e aquisições (M&A) e a sucessão nas empresas.`;

export const HenriqueBravo = `Em breve.`;

export const ItaloMartinsDeOliveira = `Médico formado pela Universidade Federal do Ceará (UFC), com doutorado pelo Instituto do Coração do Hospital das Clínicas da Faculdade de Medicina da Universidade de São Paulo (INCOR/FMUSP) e especialização em Cardiologia e Geriatria por programas do Brasil e do exterior. MBA internacional em Gestão de Projetos pela Fundação Getúlio Vargas (FGV/SP). Na área da saúde, ocupou diversas funções de direção em hospitais e empresas e atuou em cargos públicos, municipais e estaduais, na região Nordeste. É conselheiro certificado pela FGV e tem como áreas de interesse as fusões e aquisições (M&A), a digitalização e a liderança.`;

export const ManoelCarnaubaCortez = `Engenheiro químico pela Universidade Federal da Bahia (UFBA), com MBA em Administração de Empresas pela Fundação Getúlio Vargas (FGV) e cursos de especialização em gestão e tecnologias ligadas à indústria do petróleo. Desde 1982 atuando nesse setor, ocupou diversos cargos de direção. Sua experiência e seu conhecimento se concentram nos assuntos ligados à internacionalização e à cultura organizacional.`;

export const PauloSardinha = `Luso-brasileiro, formado em Psicologia, com uma pós-graduação em Educação e outra em Processos e Dinâmicas de Grupos. Presidente da Associação Brasileira de Recursos Humanos (ABRH), com sólida carreira executiva, tendo exercido, nos últimos 20 anos, o cargo de diretor de Recursos Humanos para o Brasil e a América Latina em importantes multinacionais. Membro do Conselho Empresarial de Política Trabalhista e Social da Federação das Indústrias do Estado do Rio de Janeiro (FIRJAN) e conselheiro da Confederação dos Profissionais de RH da Língua Portuguesa, sediada em Lisboa. Também possui significativa experiência no magistério como idealizador, coordenador e professor de MBA de Recursos Humanos em relevantes instituições de ensino, tendo publicado diversos artigos.`;

export const RicardoGentilPeixotoDaCosta = `Engenheiro mecânico pela Universidade Católica de Petrópolis (UCP), com mestrado em Administração pelo IBMEC e diversas especializações em tecnologia e gestão. Atua desde 1985 na indústria aeronáutica e aeroespacial, no Brasil e no exterior, ocupando cargos executivos e em conselhos de administração. Possui ampla experiência em assuntos de liderança, cultura organizacional e internacionalização. É conselheiro certificado pela Fundação Getúlio Vargas (FGV).`;

export const RoqueMartins = `Graduado em Ciências Contábeis e mestre em Administração de Empresas pela Universidade de Fortaleza (Unifor), com MBA em Finanças, Auditoria e Controladoria pela Fundação Getúlio Vargas (FGV), pós-graduação em Gestão e Estratégia pela Universidade Federal do Ceará (UFC) e Administração Financeira pela Universidade Estadual do Ceará (UECE). Em mais de 25 anos de carreira, ocupou posições estratégicas e de liderança nas áreas financeira, de controladoria e de auditoria em diversas empresas, atuando também como docente em cursos de pós-graduação. Suas áreas de concentração incluem ESG (Ambiental, Social e Governança) e GRC (Governança, Riscos e Compliance).`;

export const SergioAraujo = `Formado em Engenharia Química, com mestrado em Logística pela Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio) e cursos de pós-graduação em Segurança e Proteção Ambiental e em Engenharia Econômica. Atuando na indústria química e de petróleo e gás, na qual ocupou cargos de direção e em conselhos de empresas, tem experiência em implantação de conselhos e em assuntos ligados a ESG (Ambiental, Social e Governança).`;

export const TelmoBauler = `Gestor Imobiliário com mais de 15 anos de atuação nos diversos segmentos do Construbusiness. É especialista em negócios imobiliários/construção civil e melhoria da qualidade, trabalhando como consultor e conselheiro em gestão empresarial. Possui vivência e conhecimento das diferenças setoriais e culturais do setor nas regiões Sul e Sudeste do Brasil.`;